name: jejulogis
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^4.5.0
  dio: ^5.8.0+1
  get: ^4.6.1
  intl: ^0.20.2
  pretty_dio_logger: ^1.1.1
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.4
  carousel_slider: ^5.1.1
  page_view_indicators: ^2.0.0
  flutter_spinkit: ^5.1.0
  json_annotation: ^4.4.0
  kpostal: ^1.1.0
  url_launcher: ^6.0.20
  webview_flutter: ^4.10.0
  js: ^0.7.1
  keyboard_dismisser: ^3.0.0
  clipboard: ^0.1.3
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.7
  build_web_compilers: ^4.0.11
  retrofit_generator: ^7.0.8
  json_serializable: ^6.1.3


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/button/
    - assets/button/google/
    - assets/agreement/
    - assets/images/
    - assets/images/new_banner/
    - assets/texts/
  fonts:
    - family: SpoqaHanSans
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf
